version: '3.1'

services:
  mongodb:
    image: 'mongo:6.0'
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=replicaset
      - MONGODB_EXTRA_FLAGS=--bind_ip_all
    volumes:
      - volume-mongo:/data/db
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack}'
    image: localstack/localstack:3
    network_mode: bridge
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - USER=root
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SECRET_KEY=test
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DOCKER_CMD=colima
      - DNS_ADDRESS=localhost
      - DNS_LOCAL_NAME_PATTERNS='.*(sns|sqs).ca-central-1.amazonaws.com'
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - SKIP_SSL_CERT_DOWNLOAD=1
      - AWS_REGION=ca-central-1
    volumes:
      - volume-localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack:/etc/localstack/init/ready.d
volumes:
  volume-mongo:
  volume-localstack:
