name: "Request Reviewers"

on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  request-reviewers:
    if: '! github.event.pull_request.draft'
    name: Request reviews on opened PRs
    runs-on: ubuntu-latest

    steps:
      - name: Add Pull Request Reviewers
        uses: rhs/add-reviewer-gh-action@1.0.6
        with:
          team_reviewers: "reviewers"
          token: ${{ secrets.GITHUB_TOKEN }}
